Major cleanup.

diff --git a/bin/ssh-h-config b/bin/ssh-h-config
--- a/bin/ssh-h-config
+++ b/bin/ssh-h-config
@@ -1,13 +1,17 @@
 #!/bin/sh -e
 ##:
-#h: Usage: ssh-h-config OPTS... SSH,...
+#h: Usage: ssh-h-config [OPS...] SSH,...
+#h:
+#h: This program helps editing the server's "/etc/ssh/sshd_config" file
+#h: (In windows C:/ProgramData/ssh/sshd_config) in bulk.
 #h:
 #h:   -gC1 : Get configuration file pathname.
 #h:   -gC2 : Print configuration file.
 #h:   -dP  : Disable password login.
 #h:   -r   : Restart SSHD service.
 #h:
-#h: Configure the SSH servers in machines.
+#h: Supported platforms: Linux, OpenBSD, Busybox Windows.
+#h: See also: ssh-h-list
 ##:
 . ssh-h-list
 ssh_h_config() {
@@ -17,7 +21,6 @@ ssh_h_config() {
     while getopts "gdCP12r" optopt; do
         ops="${ops}${optopt}"
         case $optopt in
-            
             \?) return 1;;
         esac
     done
@@ -39,40 +42,43 @@ ssh_h_config_file_content() {
     ssh -T "$1" "${SSH_H_GET_F} sed 's|^|$1:|' \"\$f\""
 }
 ssh_h_config_disable_password() {
-    local sed='
-    s|^\#*PasswordAuthentication .*|PasswordAuthentication no|
-    '
+    local sed='s|^\#*PasswordAuthentication .*|PasswordAuthentication no|'
     echo "Disabling SSH password login in ${1} ..."
     ssh -T "$1" "${SSH_H_GET_F} \${sudo} sed -i '${sed}' \"\$f\""
 }
 ssh_h_config_restart() {
     echo "Restarting SSH service in ${1} ..."
     ssh -T "$1" '
-    if test @"$(uname -o)" = @"MS/Windows"; then
-        sc stop sshd; sc start sshd
-    elif test @"$(uname -o)" = @"GNU/Linux" && test -e /lib/systemd/system/ssh.service; then
-        sudo systemctl restart sshd
-    else
-        echo >&2 "error: Unknown platform."
-        exit 1
-    fi
+        if test @"$(uname -s)" = @"Windows_NT"; then
+            sc stop sshd; sc start sshd
+        elif test @"$(uname -s)" = @"Linux" && test -e /lib/systemd/system/ssh.service; then
+            sudo systemctl restart sshd
+        else
+            echo >&2 "error: Unknown platform."
+            exit 1
+        fi
     '
 }
 ## -------------------------------------------------------------------
 SSH_H_GET_F='
-    if test @"$(uname -o)" = @"MS/Windows"; then
+    if test @"$(uname -s)" = @"Windows_NT"; then
         f="C:/ProgramData/ssh/sshd_config"
         sudo=
-    elif test @"$(uname -o)" = @"GNU/Linux"; then
+    else
         f="/etc/ssh/sshd_config"
         sudo=sudo
+    fi
+    if test -w "$f"; then
+        true
+    elif which sudo >/dev/null 2>&1; then
+        sudo=sudo
     else
-        echo >&2 "error: Cannot find SSHD configuration file."
+        echo >&2 "error: Cannot write to $f."
         exit 1
     fi
 '
 ## -------------------------------------------------------------------
-if test @"$(basename "$0")" = @"ssh-h-config";then
+if test @"${SCRNAME:-$(basename "$0")}" = @"ssh-h-config"; then
     case "${1}" in
         ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0";;
         *)            ssh_h_config "$@"; exit 0        ;;
