m

diff --git a/bin/ssh-h-ping b/bin/ssh-h-ping
--- a/bin/ssh-h-ping
+++ b/bin/ssh-h-ping
@@ -4,13 +4,16 @@
 ##:
 ssh_h_ping() {
     local m
-    for m in "$@"; do
+    for m in $(echo "$*" | tr ',' ' '); do
         printf '%-10s : ' "${m}"
-        ssh -o PasswordAuthentication=no \
-            -o BatchMode=yes \
-            -o ConnectTimeout=2 \
-            "${m}" \
-            "uname -a | sed 's| *\\#.*||'"
+        if ! ssh \
+             -o PasswordAuthentication=no \
+             -o BatchMode=yes \
+             -o ConnectTimeout=2 \
+             "${m}" \
+             "uname -a | sed 's| *\\#.*||'" 2>/dev/null; then
+            echo "ERROR"
+        fi
     done
 }
 if test @"$(basename "$0")" = @"ssh-h-ping"; then
diff --git a/bin/ssh-h-send b/bin/ssh-h-send
--- a/bin/ssh-h-send
+++ b/bin/ssh-h-send
@@ -1,6 +1,6 @@
 #!/bin/sh -e
 ##:
-#h: Usage: $0 REMOTE:DIRECTORY FILES...
+#h: Usage: ssh-h-send REMOTE:DIRECTORY FILES...
 #h:
 #h: Send files to a remote directory using `tar(1)` and `ssh(1)`.
 ##:
@@ -8,11 +8,11 @@ ssh_h_send() {
     local ret=0
     ## Check programs.
     if ! which tar >/dev/null 2>&1;then
-        ssh_send_error "Please install 'tar(1)'."
+        echo >&2 "error: Please install 'tar(1)'."
         local ret=1
     fi
     if ! which ssh >/dev/null 2>&1;then
-        ssh_send_error "Please install 'ssh(1)'."
+        echo >&2 "error: Please install 'ssh(1)'."
         local ret=1
     fi
     if test ! @"${ret}" = @"0";then
@@ -20,17 +20,17 @@ ssh_h_send() {
     fi
     ## Get remote.
     if test ! -n "${1}";then
-        ssh_send_error "Please specify a destination."
+        echo >&2 "error: Please specify a destination."
         return 1
     fi
     local ssh="`printf '%s\n' "${1}" | sed -n 's|:.*||p'   `"
     local dir="`printf '%s\n' "${1}" | sed -n 's|^.*:||p'  `"
     if test ! -n "${ssh}";then
-        ssh_send_error  "No hostname: ${1}." >&2
+        echo >&2 "error: No hostname: ${1}." >&2
         return 1
     fi
     if test ! -n "${dir}";then
-        ssh_send_error  "No directory: ${1}." >&2
+        echo >&2 "error: No directory: ${1}." >&2
         return 1
     fi
     shift
@@ -41,10 +41,8 @@ ssh_h_send() {
     ## Send.
     tar czf - "$@" | ssh "${ssh}" "if cd '${dir}';then tar xvzf -;fi"
 }
-## -----------------------------------------------------------------------------
-ssh_send_error() { echo "${SCRNAME}: error: $*" >&2; }
-SCRNAME="`basename "$0"`"
-if test @"${SCRNAME}" = @"ssh-h-send";then
+## -------------------------------------------------------------------
+if test @"$(basename "$0")" = @"ssh-h-send";then
     case "${1}" in
         ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0";;
         *)            ssh_h_send "$@"; exit 0;;
